apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

patches:
  - path: patch-replicas.yaml

commonLabels:
  environment: dev

images:
  - name: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/handson-flask-api
    newTag: latest   # ArgoCD Image Updater will update this
